### ISSUE TITLE
unable to read Date and Time from xl into R

### ISSUE THREAD

**Issue by vin6381** [tidyverse/readxl#280]
I am unable to read Date and Time form xl sheet into R.
I have separate Date column and Time column. when ever load into R using readily::read_excel
it gives 08-01-1904 08:00:00
using R studio 1.0.136
R package 3.3.2
mac user 
just a file is added as an sample 
[Try.xlsx](https://github.com/tidyverse/readxl/files/816329/Try.xlsx)

**Comment by jennybc** [comment]
<img width="372" alt="screen shot 2017-03-03 at 2 40 54 pm" src="https://cloud.githubusercontent.com/assets/599454/23571943/d696dbf8-0020-11e7-9a15-86d3cf78c991.png">


Here's what I get:

``` r
readxl::read_excel("~/Downloads/Try.xlsx")
#> # A tibble: 1 × 4
#>   componet_Date        Componet_Hrs            `AF Hrs`
#>          <dttm>              <dttm>              <dttm>
#> 1    2017-10-03 1904-01-10 14:10:00 1904-01-10 20:10:00
#> # ... with 1 more variables: `Balance Hrs` <dttm>
```

`componet_Date` appears to come in as the date I see in Excel.

Then ... `Componet_Hrs` and `AF Hrs`are mean to be ... what? Times of day? They are date-times in 1904 right now, but with formatting applied so they display only the hours and minutes since time origin (230 and 236 hours, respectively). What do they mean and what result do you expect?

I suspect the underlying data is not what you intend it to be and you've applied some formatting to make things appear more like you want. But that doesn't change the underlying data problem. And readxl can only import the date-time data that is actually present in the sheet.

**Comment by vin6381** [comment]
Componet_date is date of installation only 
Componet_hrs is component total hrs component can run
AF_hrs is the AF hrs is total hrs Airframe and component flow in total 
Bal_hrs is  component_hrs -aF_hrs 
Example 
A component has total 360 hrs it can operate 
Af_hrs is hrs flown 
example 100 hrs 

Bal_hrs = 360-100 
               = 260 hrs it can fly or operate till next 260 hrs 


Vineet sharma

**Comment by jennybc** [comment]
Ok yes, you do not want to use date times for `Componet_hrs` or `AF_hrs`, which are time durations, not times of day. 

I think the tips here and in other searches for "excel time duration" should help you enter and format such data in Excel:

http://stackoverflow.com/questions/16912568/working-with-time-duration-not-time-of-day
