### ISSUE TITLE
Extend support for extensionless files

### ISSUE THREAD

**Issue by stephlocke** [tidyverse/readxl#342]
1. It'd be nifty if `read_excel()` will try the lower level functions if it does not detect an extension
2. More importantly, `excel_sheets()` needs support for extensionless files

**Comment by jennybc** [comment]
Reminding myself of context: Shiny will strip file extension (although I hold on to some hope that this will change one day https://github.com/rstudio/shiny/issues/1501). So there is no easy way for Shiny app developer to take advantage of the new functions `read_xls()` or `read_xlsx()`. Because *they* don't know if its `xls` or `xlsx`. The workaround is to try `read_xlsx()` and catch the error, in which case try again with `read_xls()`. That doesn't help with `excel_sheets()`, though.

**Comment by jennybc** [comment]
Detect format with something along these lines (suggestion from @jimhester):

```r
## https://en.wikipedia.org/wiki/List_of_file_signatures
readBin(no_ext_xls, n = 8, what = "raw")
#> [1] d0 cf 11 e0 a1 b1 1a e1
readBin(no_ext_xlsx, n = 4, what = "raw")
#> [1] 50 4b 03 04
```
