### ISSUE TITLE
hidden lines

### ISSUE THREAD

**Issue by RobertMyles** [tidyverse/readxl#351]
Hi,

First, thanks for the great work on the readxl package, the new version looks great.

Second, is there any way to deal with the "hidden" lines that come out of a dynamic table? My colleagues work with these types of tables in Excel, which I then import into R and promptly have a fit. The reason is that many observations are hidden (where the value would be repeated), with a little plus sign beside the empty cell. So, for example, a table like this:  

| var1  | var2 |
| ------------- | ------------- |
| Yes  | 0.3  |
|   | 0.2  |
| No | 0.3|

In this table, Excel avoids repeating "Yes". I can expand the column values in Excel, write to csv etc etc, but when I read straight from the worksheet with `read_excel()`, I can't figure out how to fill in these values. Any ideas? I haven't seen this mentioned in the vignettes or the release notes for the new release, is it something that I can do with readxl?

**Comment by jennybc** [comment]
I'm relieved you aren't asking about actual hidden rows because I haven't implemented that yet! Or maybe you are? I can't quite tell and would need to see an example sheet.

Based on what I see in your example, this is what's called "last observation carried forward" (LOCF). I have also referred to it as "shit trickles down".

`tidyr::fill()` is built for exactly this.

**Comment by RobertMyles** [comment]
Fantastic, thanks for the quick response @jennybc ! That was what I was referring to. I'll close this issue so. Thanks again.
