### ISSUE TITLE
Error reading xls file

### ISSUE THREAD

**Issue by rsbivand** [tidyverse/readxl#362]
There is a silent failure in read_excel in reading Polish presidential election results files - the files have the same local authority unit identifiers, but read_excel sets numeric zero for all identifiers:

```
td <- tempdir()
setwd(td)
download.file("http://prezydent2015.pkw.gov.pl/prezydent_2015_tura1.zip", "prezydent_2015_tura1.zip")
print(unzip("prezydent_2015_tura1.zip"))
library(readxl)
summary(read_excel("wyniki_tura1-1.xls")$`TERYT gminy`)
summary(read.csv2("prezydent_2015_tura1.csv", fileEncoding="CP1250", stringsAsFactors=FALSE)$TERYT.gminy)
```

I have a feeling that I've seen this before. Now using `readxl_1.0.0`, but same result with `readxl_1.0.0.9000`.

**Comment by jennybc** [comment]
This is some combination of an unusual xls file and a bug in libxls.

The cells in question are character formulas and should be imported as text. I presume they have this treatment in order to preserve the leading zeroes? 

<img width="256" alt="screen shot 2017-05-12 at 12 33 54 am" src="https://cloud.githubusercontent.com/assets/599454/25987938/dfb4e2b4-36aa-11e7-85f9-a21f145664f1.png">

The csv lacks these zeroes, so this column imports as integer. The csv has other difference with the Excel file, such as having a different number of variables. But the csv is neither here nor there.

The cells in the column of interest are incorrectly marked by libxls as *numeric* formulas, having the value of 0, hence the result you see.

If I open the file in Excel and re-save, even as xls, readxl imports it correctly.

``` r
library(readxl)
read_excel("~/tmp/wyniki_tura1-1.xls", range = "A1:D6")
#> # A tibble: 5 x 4
#>    Województwo          Gmina `TERYT gminy` `Numer obwodu`
#>          <chr>          <chr>         <chr>          <dbl>
#> 1 dolnośląskie m. Bolesławiec        020101              1
#> 2 dolnośląskie m. Bolesławiec        020101              2
#> 3 dolnośląskie m. Bolesławiec        020101              3
#> 4 dolnośląskie m. Bolesławiec        020101              4
#> 5 dolnośląskie m. Bolesławiec        020101              5
```

Ditto if I save as xlsx.

``` r
library(readxl)
read_excel("~/tmp/wyniki_tura1-1.xlsx", range = "A1:D6")
#> # A tibble: 5 x 4
#>    Województwo          Gmina `TERYT gminy` `Numer obwodu`
#>          <chr>          <chr>         <chr>          <dbl>
#> 1 dolnośląskie m. Bolesławiec        020101              1
#> 2 dolnośląskie m. Bolesławiec        020101              2
#> 3 dolnośląskie m. Bolesławiec        020101              3
#> 4 dolnośląskie m. Bolesławiec        020101              4
#> 5 dolnośląskie m. Bolesławiec        020101              5
```

This usually means the original xls was written by something other than Excel and its doing something nonstandard that libxls does not anticipate. I've tracked down and fixed a few of these bugs in libxls, but it's really painstaking. There would have to be a lot of these peculiar sheets to make it worth it.

**Comment by rsbivand** [comment]
Thanks for your rapid response. I've contacted the data publisher to see whether they are willing to say how the offending file was produced, CC to @pbiecek.

**Comment by rsbivand** [comment]
The work-around - read into Excel and write out again - works for me for Excel 2013. The output file is somewhat larger (was 12.8MB, became 13.3MB). The use of =TEXT(<cell>, "<string>") is given as advice [here](https://support.office.com/en-us/article/Keep-leading-zeros-1bf7b935-36e1-4985-842f-5dfa51f85fe7). You see ="<string>" and '<string> on SO too.

**Comment by rsbivand** [comment]
The data provider replies that they generated CSV files using a one-off sed script. Now the TERYT fields are text-formatted in Excel. So it's an isolated case. I'm impressed that they got back to me in 3.5 hours.
