### ISSUE TITLE
predict coltypes before reading.

### ISSUE THREAD

**Issue by ilpepe** [tidyverse/readxl#364]
Hi,
 I need to read excel sheet that can differ in number of column.
However as some column start with empty cells, the col_type predicting is wrongly set to boolean for these columns.
The sheet contains a mixed number of coltypes, like text and numeric.
I know the colnames for the cols that are text formatted.

the idea now would be to fetch the number of columns, fetch the col names, set everything to col_type numeric , except for the colnames that are being picked up for col_type text.
However I don't find a way to do this.

Google gave me this command:
readxl:::xlsx_col_types(excel.file, sheet =   sheet.num, nskip = 0, n = 1))

However I get 

> readxl:::xlsx_col_names(data_file, sheet = "Data")
 
> Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
> object 'xlsx_col_names' not found

Is this function removed? How should I proceed.

**Comment by jennybc** [comment]
At this very moment, you will need to do a preliminary read, using `n_max` to minimize rows read, in order to learn the number of columns and/or their names.

Then you should be able to form a `col_types` vector programmatically for the 2nd and main read.

We already want to give readxl a readr-like interface for column types (#198), which would give you more attractive options. This is why I am very reluctant to build in any more "smarts" to the existing system. That's why I'm suggesting the 2-read workaround.

**Comment by jennybc** [comment]
Yes `xlsx_col_names()` was removed. It was never exported so it was a surprise to me that people were using it. It was never used internally. You can emulate it with `n_max = 0`.

``` r
library(readxl)
names(read_excel(readxl_example("datasets.xlsx"), n_max = 0))
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width" 
#> [5] "Species"
```

**Comment by ilpepe** [comment]
Thanks for the info.
Actually found quiet some info on the xlsx_col_names.
Anyway thanks for the awesome fast  and useful reply. I'll try it right now.
