### ISSUE TITLE
read_excel renames non unique column names with col_names parameters was set to TRUE

### ISSUE THREAD

**Issue by melikovk** [tidyverse/readxl#367]
read_excel used to import column names as is and ignore empty columns when col_names parameters was set to TRUE. In a last update it renames non unique names and adds empty columns with X__ names. Is this an intended behaviour? Can one revert to old behaviour? I would think this is inconsistent with the tidyverse's approach of simplicity. Anyone who wants to get unique names can easily use tidy_names() function or make.unique and I guess it is safe to assume that if you set col_names to true you named all needed columns to your liking.
Thank you.

**Comment by jennybc** [comment]
> I would think this is inconsistent with the tidyverse's approach of simplicity

It's actually the opposite. We're trying to have a tidyverse-wide name repair strategy and readxl is now using a function in tibble to repair names, versus rolling it's own treatment.

Ditto for columns that have no name. readr, for example, does not drop a column just because the column name is empty. Therefore neither should readxl. I may have misunderstood you, though, because I can't tell if you're talking about *empty columns* or *empty column names* above.

I think most people do not have control over the column names in the Excel file and frequently need to repair them in R. We do enough name repair to make it a valid tibble and then the user should take it from there.

**Comment by melikovk** [comment]
Thank you for clarification, I will modify my code. I think in one of the old vignettes not munging column names was listed as one of the reasons to use readr over base functions. In my opinion it was a convenient feature. As for the column names I observe the following behaviour. I have a table of this structure:
Name1 Name2 Empty Name1 Name2 ...
Value1 Value2  Empty  Value3 Value4 ...
....
I get the following:
Name1 Name2 X__1 Name1__1 Name2__1 ...
Value1 Value2    NA   Value3        Value4 ...
....

So it is both empty column name and empty column.
Thank you.

**Comment by jennybc** [comment]
> not munging column names was listed as one of the reasons to use readr over base functions

The munging that we do is aimed specifically at these two problems: empty names and duplicate names. Because they leave you with an invalid tibble. We still don't repair names to make them syntactic. But, yes, there has definitely been refinement over the past 1-2 years about where to draw the line.

As for your example, yes, readxl no longer drops embedded empty columns. That is motivated by the desire to be more like readr:

``` r
readr::read_csv("V1,,V3\n1,,3\na,,c")
#> Warning: Missing column names filled in: 'X2' [2]
#> # A tibble: 2 x 3
#>      V1    X2    V3
#>   <chr> <chr> <chr>
#> 1     1  <NA>     3
#> 2     a  <NA>     c
```

(Note that readr isn't using tibble's name repair yet but it will eventually!)

**Comment by melikovk** [comment]
Not to start long discussion, but just as my personal opinion, i think it was more convenient to leave duplicate names as is. It is trivial to fix it if you need to and it is more convenient to use (in my opinion) for downstream processing. In case of empty columns I think that there is a difference between csv and excel file. In csv empty column is explicit (you have put extra comma to create it) while in excel files they are often used as a formatting tool to improve readability. In any case thank you for working on readxl and for the clarification.
