### ISSUE TITLE
Add function to read all sheets into a list

### ISSUE THREAD

**Issue by sncr-github** [tidyverse/readxl#407]
Suggestion:  add a function to read all available sheets into a list.   Simple version below:

```
library(readxl)

read_all_excel<-function(file){
 sheets <- list()
 idx <- 1
 sheet_names <- excel_sheets(file)
 for (s in sheet_names){
  sheets[[idx]] <- read_excel(file, sheet = s)
  idx <- idx + 1
 }
 names(sheets) <- sheet_names
 return(sheets)
}
```

Pros:  
* A convenience for immediately reading in all sheets.

Cons:  
* Dataframes are the usual "top level object" in the Tidyverse.  
* Version as shown does not include additional function arguments available in excel_sheets. This is less confusing and suggests that individuals with special requirements per sheet implement their own.

**Comment by cderv** [comment]
I find it pretty simple to combine `readxl` with `purrr` functions, as shown also in vignette _workflows_

```r
path <- readxl_example("datasets.xlsx")
path %>% 
  excel_sheets() %>% 
  set_names() %>% 
  map(read_excel, path = path)
```

Using `map_df`, you can also get a data.frame if all your sheets are containing same data
```r
path <- readxl_example("deaths.xlsx")
deaths <- path %>%
  excel_sheets() %>%
  set_names() %>% 
  map_df(~ read_excel(path = path, sheet = .x, range = "A5:F15"), .id = "sheet")
```

I think relying on `purrr` functions for iterating through sheets offers great flexibility.

**Comment by jennybc** [comment]
Adding a link to the vignette @cderv refers to:

http://readxl.tidyverse.org/articles/articles/readxl-workflows.html

I absolutely see the utility of this but am on the fence re: a built-in function for it. Which is why I wrote the vignette.

Obviously if this was typical use for most users, it's a no brainer to bring it into readxl. As a user, I have the occasional spreadsheet that I treat this way, but it's the exception rather than the rule. Worth discussing, though.

**Comment by jennybc** [comment]
I still think this is a matter to handle via documentation (and this exists in our current documentation). It doesn't require too much code to do this in a base R or tidyverse style.
