### ISSUE TITLE
Decimals in read_excel

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/readxl#423]
![capture](https://user-images.githubusercontent.com/18138496/36085090-30202b98-0fd4-11e8-99e7-97d6030651ca.PNG)
I am using readxl read excel sheets.

However, I realized that the following 
one cell contains 0.212 but it shows in MS Excel as 0, and after I import to R using readxl, it shows as 0.21199999999999999

Also When I used na = c("", "...") in read_excel, is not working.

**Comment by batpigandme** [comment]
We can't look into this without the code and the data.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:
1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
2.  Share via DropBox or Google Drive and provide the link in your issue.
3.  Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
4.   Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by msgoussi** [comment]
[WPP2017_POP_F07_2_POPULATION_BY_AGE_MALE.zip](https://github.com/tidyverse/readxl/files/1719857/WPP2017_POP_F07_2_POPULATION_BY_AGE_MALE.zip)

When you open the file (ESTIMATES Sheet) and you filter the C column by Tonga, Cell X3386 is 0, but when you click on the cell, it is 0.174.

If you use R
x <- readxl::read_excel("WPP2017_POP_F07_2_POPULATION_BY_AGE_MALE.xlsx", 1, skip = 16)
View(x[3369, ])
you will the same cell is 0.17399999999999999

I am using Windows 10 x64.
Please advise.

**Comment by msgoussi** [comment]
but the number in Excel is 0.174 (Exactly not formatted at all), why it
shows 0.17399999999999 in R

**Comment by jimhester** [comment]
The numbers imported in R are the actual numeric values contained in the saved file. Excel is rounding the numbers to a fixed precision when it displays them (by default 4 decimal places).  See [Understanding Floating Point Precision, aka “Why does Excel Give Me Seemingly Wrong Answers?”](https://blogs.office.com/en-us/2008/04/10/understanding-floating-point-precision-aka-why-does-excel-give-me-seemingly-wrong-answers/)

At the end of that article it mentions an excel option **Set precision as displayed**, which will save the file with only the precision which is displayed. This will ensure the numbers are imported in R exactly as you see them in excel. _However_ setting this option is dangerous because it actually destroys information and may lead to (much) greater errors when doing arithmetic with floating point numbers.

**Comment by nacnudus** [comment]
The option **Set precision as displayed** has no effect in this case, where the particular problem is that 0.174 doesn't have an exact binary representation.  Excel rounds the number to the [nearest binary representation](http://www.binaryconvert.com/result_double.html?decimal=048046049055051057057057057057057057057057057057057057057) before converting it back to decimal (further rounding) and saving it to disk.

It shouldn't cause any trouble, because in R `0.174 == 0.17399999999999999` is `TRUE`.   Though you should consider using something like `all.equal()` when comparing floating point numbers.

**Comment by NoushinN** [comment]
To follow up on this issue, facing the same problem:
```
x =992813.01 in .xls file and once it is read in R, it turns into x = 992813.0999999 

```
Is there a way to import data from xls to R without modifying floating point decimal points?

**Comment by jennybc** [comment]
I don't have anything to add to the discussion above, no. The number you see in Excel -- ending in `.03` -- does not actually exist on disk. It is a floating point number that is rounded by the Excel application to produce something for consumption by human eyeballs. You may need to work on these numbers on the R side, e.g. via rounding, to produce the result you want.

**Comment by NoushinN** [comment]
on to post-fix then, @jennybc thank you for your quick reply

**Comment by LeZhengThu** [comment]
If you create an empty Excel, manually input X number with decimals, read the excel with read.xlsx, there would randomly appear Y crazy decimals. This is an openxlsx issue.

**Comment by ymao2329** [comment]
I believe the read_excel() function treats those numbers as characters, making them look like long infinite decimals. The same issue was troubling me just now, I found it goes normal after I applied as.numeric().

Before
![image](https://user-images.githubusercontent.com/113373707/208145163-aedd5edd-27e0-4622-a9ce-e0fc839e4522.png)

After
![image](https://user-images.githubusercontent.com/113373707/208146078-0dfba1d6-6f40-4f55-bf04-11820525892c.png)

**Comment by jennybc** [comment]
> I believe the read_excel() function treats those numbers as characters

That means either readxl was told to import that column as character, via `col_types`, or readxl was told to guess the column type from the data and there is at least 1 non-numeric cell.
