### ISSUE TITLE
question/feature request

### ISSUE THREAD

**Issue by bellafeng** [tidyverse/readxl#424]
Column names is a question: Done?(y/n). After reading in, I had to put quotation mark on the question to refer to this column as below. 
test_xl<- read_excel("~/test.xlsx")
test_xl$`Done?(y/n)`

In SAS, when I do import like this, I think (if memory serves) SAS generate variable names like Done_?_y_n which is appealing so that I can use names(test_xl) to get the names into a vector. 
In using read_excel, however, this names is not different from regular dataset: names(iris) for example. But it's hard to refer them in the next step without adding " " to the names.
Hope I explained myself clearly. (my first issue report, Jenny/Hadley, so be gentle. :))

**Comment by bellafeng** [comment]
[test.xlsx](https://github.com/tidyverse/readxl/files/1729631/test.xlsx)

**Comment by jimhester** [comment]
You can always refer to so-called non-syntactic names with backticks ``. However if you want to transform the names to syntactic you can use `tibble::set_tidy_names(syntactic = TRUE)`, which will convert any non-syntactic characters to `.`, e.g.

```r
dat <- readxl::read_xlsx("test.xlsx")
dat$`Done?(y/n)`
#> [1] "Y" "N" "Y" "N"

dat2 <- tibble::set_tidy_names(dat, syntactic = TRUE)
dat2$Done..y.n.
#> [1] "Y" "N" "Y" "N"
```

**Comment by jennybc** [comment]
Yes what @jimhester says.

It's a *de facto* convention for data import packages in the tidyverse to *not* mess with variable names. Why? Because faithfully using what's found in the file is completely objective and predictable, whereas munging them into something friendly can be done in countless ways.

We want you, the user, to take responsibility for the name munging (or to use backticks). So it's tough love. But still love 💜
