### ISSUE TITLE
how to use xts/zoo with readxl (or tibbles)

### ISSUE THREAD

**Issue by Jmarks199** [tidyverse/readxl#427]
Please disclose upon attachment what functions are made unusable in zoo / xts as a result of attaching the readxl package.

For instance, attaching this package makes xts::xts() not function properly. I assume because of their read.zoo function.

With "dates" as the first column of our data.frame / tibble read in from readxl:

`data$dates <- as.POSIXct(data$dates, format = '%Y-%m-%d')`
`data <- xts(data[,-1], order.by = data[,1])`

    Error in xts(data[, -1], order.by = data[, 1]) : 
    order.by requires an appropriate time-based object`

Detaching the package fixes the issue. Thank you,

**Comment by batpigandme** [comment]
Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)?  I'm not able to see where the namespace collisions are occurring.

**Comment by jimhester** [comment]
Actually the reason for this is likely because readxl returns `data` as a [tibble](http://tibble.tidyverse.org/), and dimensions are not dropped automatically by tibbles (unlike `data.frame`'s).

`data <- xts(data[,-1], order.by = data[[1]])` or `data <- xts(data[,-1], order.by = data[,1, drop = TRUE])` should work, or `data <- as.data.frame(data)` before your manipulations.

FWIW detaching readxl "fixes" the problem because the tibble package is unloaded, so you no longer get this behavior from tibbles (which act as normal data.frames if the tibble package is not loaded).

**Comment by jimhester** [comment]
For reference here is a reprex of the problem and a solution, it can actually be reproduced without readxl at all

``` r
library(tibble)
library(xts)
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
data <- as_tibble(mtcars)
data$dates <- sample(seq(as.Date('1999/01/01'), as.Date('2017/01/01'), by="day"), nrow(mtcars))
data <- data[, c("dates", setdiff(names(data), "dates"))]
data <- xts(data[,-1], order.by = data[,1])
#> Error in xts(data[, -1], order.by = data[, 1]): order.by requires an appropriate time-based object
data <- xts(data[,-1], order.by = data[[1]])
str(data)
#> An 'xts' object on 2000-03-16/2016-05-21 containing:
#>   Data: num [1:32, 1:11] 33.9 17.8 15.2 26 14.7 19.7 10.4 21.4 16.4 21 ...
#>  - attr(*, "dimnames")=List of 2
#>   ..$ : NULL
#>   ..$ : chr [1:11] "mpg" "cyl" "disp" "hp" ...
#>   Indexed by objects of class: [Date] TZ: UTC
#>   xts Attributes:  
#>  NULL
```

Created on 2018-02-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
