### ISSUE TITLE
Estimated timeframe of a new CRAN version

### ISSUE THREAD

**Issue by KyleHaynes** [tidyverse/readxl#433]
Hi,

I really don't want to be seen as pestering the project team, so wondering if this is appropriate to even post here? Please let me know if so and i'll refrain from doing so in the future (across any tidyverse package).

Is there an ETA on when a new version of readxl will be submitted to CRAN?

If  [past history](https://cran.r-projct.org/src/contrib/Archive/readxl/) is to go by, it appears to be yearly and around this time of year ... this could just be coincidence though.

Thanks muchly

**Comment by jennybc** [comment]
I don't have a concrete plan but yes I'm starting to do work here these days. What's in (or could be in) a new release that motivates you to inquire?

**Comment by elyksenyah** [comment]
Mainly the below two fixes:  
https://github.com/tidyverse/readxl/issues/410  
https://github.com/tidyverse/readxl/issues/430

As for what could be in it ... nothing really comes to mind, I've done a quick scan through the current open issues and nothing jumps out besides this:
https://github.com/tidyverse/readxl/issues/407

I'm also on the fence, we regularly deal with requiring the importation of multiple worksheets, to the point that we created a similar function that deals with exactly that (hence when testing it, identified #430 issue above).

Thanks for this package BTW ... it's certainly one of the main reasons I've been able to completely move away from using Excel in my personal life (to a point I don't have MS Office installed on my home PC). Unfortunately, due to the addiction of the spreadsheet ... not so much at work.

**Comment by batpigandme** [comment]
@KyleHaynes if you haven't done so already, please toss a `:+1:` (aka 👍) on those issues. We're starting to keep track of those as a way of seeing what's most pressing for users (deets to follow in a post soon), so that helps.

If you have a new issue, feel free to open one. Otherwise, I'm going to close this thread as an "issue", since it really isn't one, per se. (@jennybc, obviously feel free to override).

**Comment by KyleHaynes** [comment]
Will do. Thanks Mara!
