### ISSUE TITLE
suggestion: tidycols()

### ISSUE THREAD

**Issue by randallhelms** [tidyverse/readxl#484]
This isn't a bug so much as a feature suggestion. One thing that I have noticed when working with Excel workbooks that are provided by non-data colleagues (like marketers, business development, finance people, etc) is that the columns are often named in a very R-unfriendly way, so I wrote a function a while back that automatically converts the column names to snake case and lower-case. Maybe it might be a useful function to add to the package, or to bake into the basic read_excel() function as an argument?

```r
tidycols <- function(df) {
  require(snakecase)
  require(stringr)
  
  dfnames <- colnames(df)
  
  dfnames <- to_snake_case(dfnames,sep_out = "_")
  
  #list some commonly used word separators
  commonseps <- c(' ','.','-','/')
  
  dfnames <- tolower(str_replace_all(dfnames,fixed(commonseps),"_"))
  
  colnames(df) <- dfnames
  
  return(df)
}
```
I've also attached a test file, with several different column name formats, which you can use to test this function:
[test_tidycols.xlsx](https://github.com/tidyverse/readxl/files/2067139/test_tidycols.xlsx)

**Comment by cderv** [comment]
Hi, 

FWIW there is `janitor` 📦 that could help, not from tidyverse but _tidyverse oriented_ . It has a special [`clean_names`](https://github.com/sfirke/janitor#cleaning-dirty-data) that is core of the package and does what you want. 

``` r
library(readxl)
library(magrittr)
xlsfile <- tempfile(fileext = ".xslx")
download.file("https://github.com/tidyverse/readxl/files/2067139/test_tidycols.xlsx", destfile = xlsfile, mode = "wb")
tab <- read_excel(xlsfile)
names(tab)
#> [1] "column one" "Column.2"   "Column-3"   "column/4"   "column_5"
tab %>% janitor::clean_names() %>% names()
#> [1] "column_one" "column_2"   "column_3"   "column_4"   "column_5"
```

Created on 2018-06-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I think it is a good idea that such cleaning functions are in their own package as they are needed for all unclean data, not just excel files. (but yes, most often unclean data are coming from excel)

I am curious what you think about this. Do you know about `janitor` 📦 ?

**Comment by jennybc** [comment]
"Not munging variable names" is an intentional policy of Tidyverse Data Ingest, to the extent that it exists officially (https://github.com/tidyverse/tidyverse/issues/34).

According to that line of thinking, only missing or replicated names are a valid reason to munge. The "official" tidyverse functions for this are `tibble::tidy_names()` and `tibble::set_tidy_names()` and the current dev version of readxl has switched to this:

https://github.com/tidyverse/readxl/blame/7bbf7fc24f40f7654dfec34b60c1a3356ad675a8/NEWS.md#L5-L9

I realize this still leaves a lot of potential munging  but everyone has different ideas about what's the right way to fix names. Therefore, I think it belongs in user code, where you can enforce your own ideas or use handy packages like janitor. I note there is also the base function `make.names()`.
