### ISSUE TITLE
read_xlsx adding trailing 0s during numeric to character conversion

### ISSUE THREAD

**Issue by seanchrismurphy** [tidyverse/readxl#574]
I'm having a weird (and difficult to reproduce) problem when reading in mixed numeric data. 

I have an excel file (exported from QuestionPro, a survey site).

One of my columns starts with:
8 9 5 "Don't know"

If I read in the only the first 3 rows using n_max, I get a numeric vector. However, when I read 4 rows, I get unexpected output:
structure(c("8.0", "9.0", "5.0", "Don't know"), class = 'character')

I've tried to replicate the problem (or provide a reprex), but if I copy the data from the problematic file into a new excel spreadsheet for testing, it reads in normally. 

In fact, in the course of testing this, I found that simply saving a new copy of the excel file fixes the problem (and increased the file size from 156KB to 169KB). 

Perhaps this is more an excel problem than a read_xl problem, but it strikes me as unexpected that read_xl reads in data differently depending on whether excel has opened/saved the file or not. What is going on under the surface here? 

Some extra info: The file was apparently created using APACHE POI

**Comment by jennybc** [comment]
I would need to get my hands on the actual original file to say for sure what's going on.

But there is a general recurring phenomenon that when 3rd party tools (so, anything but Excel) write xls(x) files, sometimes they are nonstandard. They may be readable by Excel itself, because Excel has "seen it all" and represents an enormous number of cumulative engineering hours. Excel itself can cope with a huge number of edge cases. But reading by another 3rd party tool (readxl, in this case) can be impossible or peculiar.

The fact that Excel itself re-represents this data in a different way suggests we're in that sort of situation.

All that being said ... what happens if you just specify that this column should be numeric, instead of letting the "Don't know" entries cause it to become character, leading to the conversion? After all, the main thing is to import the data into R in a correct fashion, ready for your analysis. Perhaps we don't need to tackle this other problem.
