### ISSUE TITLE
Feature request: use readr::type_convert() to match read_csv behavior

### ISSUE THREAD

**Issue by jzadra** [tidyverse/readxl#588]
Would be great if `read_excel()` output followed similar behavior to read_csv in terms of determining column types, ie:

`readxl::read_excel("data.xlsx") %>% readr::type_convert()` 

would be the default output of just running `readxl::read_excel("data.xlsx")`

**Comment by jennybc** [comment]
Can you be more specific about what would be different from readxl's current type guessing? The current column type guessing is not a cause choice. Nor can readxl just adopt what readr does because `readr::type_convert()` only operates on character data. readxl does type guessing based on full cell information in the xlsx, not on the strings it finds. In general:

https://readxl.tidyverse.org/articles/cell-and-column-types.html#type-guessing

> If you use other packages in the tidyverse, you are probably familiar with readr, which reads data from flat files. Like readxl, readr also provides column type guessing, but readr and readxl are very different under the hood.
>
>. * readr guesses column type based on the data.
>. * readxl guesses column type based on Excel cell types.
> Each cell in an Excel spreadsheet has its own type. For all intents and purposes, they are:
>
>       empty < boolean < numeric < text
>
>with the wrinkle that datetimes are a very special flavor of numeric. A cell of any particular type can always be represented as one of any higher type and, possibly, as one of lower type. When guessing, `read_excel()` keeps a running “maximum” on the cell types it has seen in any given column. Once it has visited `guess_max` rows or run out of data, this is the guessed type for that column. There is a strong current towards “text”, the column type of last resort.

**Comment by jzadra** [comment]
Hi Jenny.  That makes sense.  The immediate thing I was missing was that columns with date formats like yyyy-mm-dd were not being guessed as date, but rather staying as character.  I'll just keep using `type_convert()` after `read_excel()`

**Comment by jennybc** [comment]
Yeah we don't type-guess based on the data, because, in general, spreadsheet cells declare what sort of data they contain through other means. When importing csv, everything is a string, so you MUST guess based on the data.

If you have dates that are stored as strings, you should use some existing function on the R side that is designed to convert strings to dates. If dates are stored as dates in Excel, we bring them in as dates.

**Comment by jzadra** [comment]
Yeah.  I just have a huge number of cols with dates as strings, so I don't want to have to convert them all manually.  type_convert() works great for now.
