### ISSUE TITLE
Issue with missing values in readxl

### ISSUE THREAD

**Issue by ntsigilis** [tidyverse/readxl#599]
I am trying to import an xlsx file into R using the readxl library. In my xlsx file the missing values where coded as 99 for three numeric variables. Although I use the na="99" argument the dataframe still contains the 99 values instead of NA. I have also tried to use the RStudio build in utility "Import Dataset", "From Excell..." but the issue remained. Is there any recommendation for this problem?

Please find below the code for entering the data.

library(readxl)
STRS_selected <- read_excel("STRS selected.xlsx", na = "99")
View(STRS_selected)

**Comment by cderv** [comment]
It seems to work correctly in this small example:
``` r
iris$Petal.Length[3] <- 99
head(iris, 4)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2         99.0         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
res <- writexl::write_xlsx(iris)
head(readxl::read_excel(res), 4)
#> # A tibble: 4 x 5
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#> 1          5.1         3.5          1.4         0.2 setosa 
#> 2          4.9         3            1.4         0.2 setosa 
#> 3          4.7         3.2         99           0.2 setosa 
#> 4          4.6         3.1          1.5         0.2 setosa
head(readxl::read_excel(res, na = "99"), 4)
#> # A tibble: 4 x 5
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#> 1          5.1         3.5          1.4         0.2 setosa 
#> 2          4.9         3            1.4         0.2 setosa 
#> 3          4.7         3.2         NA           0.2 setosa 
#> 4          4.6         3.1          1.5         0.2 setosa
unlink(res)
```

<sup>Created on 2020-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Can you build a reproducible example with your data ? 

You could also check how the excel file is imported, specifically the type of columns to see if there is something odd there. 

Hope it helps.

**Comment by ntsigilis** [comment]
Dear Chistophe,

Thank you so much for the response.  Let me be clear and explain how this issue occured.  Initally, the data were in SPSS file with 99 denoting missing values.  Next, for pedagogical reasons, I export it in various file formates, including txt, csv and xlsx file and tried to import them in R using readxl.  I managed to import txt and csv files, in which 99 were imported as NA.  This was not the issue for the xlsx file.  Its worth noting the 99 in excel was appeard as 99.0000 since the inital variables in SPSS have decimal places.  I tried both na ="99" and na="99.0000", with no success. However, when I manually replaced 99.0000 with 99 it worked.

In your data set also na="99" worked. 

Thanks a lot

**Comment by cderv** [comment]
> Initally, the data were in SPSS file with 99 denoting missing values. Next, for pedagogical reasons, I export it in various file formates

Know that heaven 📦  can help you read some SPSS exported files. https://haven.tidyverse.org/index.html

> It worth noting the 99 in excel was appeard as 99.0000 since the inital variables in SPSS have decimal places. I tried both na ="99" and na="99.0000", with no success. However, when I manually replaced 99.0000 with 99 it worked.

Did you check the type of the data imported ? See the [vignette](https://readxl.tidyverse.org/articles/cell-and-column-types.html). As you don't provide reproducible example, it is just a guess: It may be possible that your excel columns with `99.000` is not seen as integer or double, but guessed as other type 🤷‍♂ 

To go forward, it is important to provide a reproducible example so that the potential bug can be identified in order to be fixed. You normally had to fill an issue template (you can found it [here](https://github.com/tidyverse/readxl/blob/master/.github/ISSUE_TEMPLATE.md)) you skipped in this issue, and that asked you to provide a [reprex](https://www.tidyverse.org/help/#reprex). Creating a reprex will help identify what is going wrong eventually. Also, you can create a sample excel file from your current one, an upload it in here if necessary. 

Hope it helps.

**Comment by jennybc** [comment]
I am guessing these 99's are recorded as doubles, so their character representation is not exactly "99" and therefore they don't match the `na` string. It's probably an example of how hard it is to test equality when floating point numbers are involved. But it's impossible to say without an actual xlsx file that demonstrates the problem.

**Comment by ntsigilis** [comment]
Dear Jenny,,
Thank you for the response. You are right that the variables were recorded as doubles.  However, the issue still holds if I change them to numeric.  Please find below the R output:

 > mydata<-read_xlsx("STRS selected.xlsx")
> head(mydata)
# A tibble: 6 x 6
     id gender   age closeness conflict dependency
  <dbl>  <dbl> <dbl>     <dbl>    <dbl>      <dbl>
1     1      1   5.5      3.08     1.25       1.14
2     2      2   5       99        1.33       1.57
3     3      2   6        3.54    99          2.43
4     4      2   6        4.08     1.67       3.29
5     5      1   6        3.77     1.75      99   
6     6      2   6        3.31     1.42       1.86
> str(mydata)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	100 obs. of  6 variables:
 $ id        : num  1 2 3 4 5 6 7 8 9 10 ...
 $ gender    : num  1 2 2 2 1 2 1 1 1 1 ...
 $ age       : num  5.5 5 6 6 6 6 6 5 6 6 ...
 $ closeness : num  3.08 99 3.54 4.08 3.77 ...
 $ conflict  : num  1.25 1.33 99 1.67 1.75 ...
 $ dependency: num  1.14 1.57 2.43 3.29 99 ...
> mydata1<-read_xlsx("STRS selected.xlsx", na="99")
> head(mydata1)
# A tibble: 6 x 6
     id gender   age closeness conflict dependency
  <dbl>  <dbl> <dbl>     <dbl>    <dbl>      <dbl>
1     1      1   5.5      3.08     1.25       1.14
2     2      2   5       99        1.33       1.57
3     3      2   6        3.54    99          2.43
4     4      2   6        4.08     1.67       3.29
5     5      1   6        3.77     1.75      99   
6     6      2   6        3.31     1.42       1.86
> str(mydata1)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	100 obs. of  6 variables:
 $ id        : num  1 2 3 4 5 6 7 8 9 10 ...
 $ gender    : num  1 2 2 2 1 2 1 1 1 1 ...
 $ age       : num  5.5 5 6 6 6 6 6 5 6 6 ...
 $ closeness : num  3.08 99 3.54 4.08 3.77 ...
 $ conflict  : num  1.25 1.33 99 1.67 1.75 ...
 $ dependency: num  1.14 1.57 2.43 3.29 99 ...

Thanks a lot

**Comment by jennybc** [comment]
Can you please use the reprex package? So I can see **all the code** you are executing and, preferably, also post the spreadsheet "STRS selected.xlsx" so I can execute your code and inspect the file? For example, above, there is clearly omitted code that relates to what you mean by "I change them to numeric".

If I try to guess what that means ... this problem can't be fixed by changing `col_type` in `read_excel()`. I suspect the difficulty is rooted in representing missing data with 99 recorded as a floating point number in the underlying xlsx.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box. `.xlsx` is a supported file type. You'll need to zip or gzip `.xls` so it appears as `.zip` or `.gz`.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.
