### ISSUE TITLE
Revise cell_cols to read specific columns?

### ISSUE THREAD

**Issue by j-sirgo** [tidyverse/readxl#616]
It appears range=cell_cols(c(2,5))

Reads the first 5 columns, but I want to read in just column 2 and column 5.

I know I can pipe and filter after but I was hoping to avoid that and perhaps speed in the import by only reading specified columns.  Any ideas?

**Comment by j-sirgo** [comment]
I was able to use the “skip” entry in col_types for the columns I don’t want and that works.

I still wonder if I can improve speed by not having the import even look at the columns I don’t want.

**Comment by jennybc** [comment]
Due to the internal implementation `range`, must always specify a rectangle that spans or covers what you want. So `cell_cols(c(2, 5))` will get columns 2, 3, 4, and 5.

As you've discovered, the way to not read embedded columns is to specify the skip type for them. This is as efficient as it gets. Given how things are stored on disk (by row), we have to at least visit these cells but if the column is skipped we never load them into memory.
