### ISSUE TITLE
Remove obsolete Excel files from package

### ISSUE THREAD

**Issue by tfulge** [tidyverse/readxl#621]
I am not sure whether if this warrants a response from you, the developers, but I am regurlarly encountering the following issue: Whenever I try to update `readxl` (or `tidyverse`) for that matter, the corporate firewall prevents me from doing so because the package contains outdated Excel files (for instance, `clippy.xls` in `/extdata`). 

The firewall prevents from getting the package via CRAN, Github and manual download. The only option I have left is to download the package on a private device and (illegally) transfer it via USB to my work pc. 

I am not sure which purpose including these files in the package has and how many others behind corporate firewalls encounter the same issue, so please feel free to close this as you see fit.

Thanks for a great package, anyways!

**Comment by jennybc** [comment]
A lot of the usage of readxl is for reading "obsolete" `.xls` files, which is why they are represented among the official example sheets. The `.xls` format is (sadly) alive and well in terms of actual usage. Many 3rd party tools are still pumping them out as I type this.

This is the first time I've heard of anyone re: being unable to install readxl for this reason. I'm surprised that this comes up when installing from the readxl CRAN binary. But in any case, it doesn't seem like a justification to change the package itself. It seems like this corporate download policy is well-intentioned, but quite impractical in reality. I'm sorry about your need to workaround.
