### ISSUE TITLE
readxl removes comma from a text column

### ISSUE THREAD

**Issue by rwbaer** [tidyverse/readxl#625]
Problem: readxl removes comma from a text column

---

I am using readxl  to read in data from files generated from a multiplate reader (example attached).  The data itself is  in B55:O102 where column O contains metadata on the excitation and emission wave lengths and indicates the blank reading for the corresponding fluorescence.  Column O is the the one that is handled in a manner that is "Possibly" buggy in readxl.  

readxl() properly (and automatically) identifies column O as a character column.  What is "wonky" is that for those rows where there are just two wave length separated by a comma, readxl "does me the favor" of removing the comma separating the two  wave lengths, as if it thinks these rows are intended to be a single large number written in business format. Interestingly, it does not provide the same  "help" in those rows that include the word Blank.  Here I get the expected behavior and the comma is maintained.  Ultimately, I want to parse column O into a blank indicator and a pair of wave lengths.  The disappearing comma on some rows makes this less straight forward.

I would understand it "helping" if the column type were numeric, but it seems just plain wrong in this context where the column is character.  I think this behavior should be classified as a "bug" when the column type is character.

```r
# path will depend on local context
Plate9_1130Export <- read_excel("H:/PlateReader/20200807 -DyeTest/Plate9_1130Export.xlsx",
                                range = "B55:O102", col_names = FALSE)
```
## read in attached example and compare right column with original Excel column
[Plate9_1130Export.xlsx](https://github.com/tidyverse/readxl/files/5051618/Plate9_1130Export.xlsx)

**Comment by jennybc** [comment]
The problem is in the Excel workbook itself. These cells really are recorded as numbers.

<img width="1050" alt="Screen Shot 2020-08-10 at 8 53 15 AM" src="https://user-images.githubusercontent.com/599454/89802929-025a6300-dae7-11ea-9117-5a9f122ee66a.png">

When I select such a cell, notice the data that is displayed in the toolbar. When I go to format this cell, notice that all the *numeric* options are pre-selected as available. The comma really isn't present in the data, so there's no way for readxl to recover it.

You need to make sure these cells are **text** cells.

So what happened? My guess is that data entry time, someone typed these, with their commas, and Excel "helped" by assuming that person really meant a number and the comma was just for marking thousands. I might have the details wrong, but the bottom line is that Excel thinks these are numbers and the commas are just a nicety for display. Therefore the commas don't exist on disk. Here's the underlying XML for the featured cell:

``` xml
<c r="O55" s="14">
<v>360460</v>
</c>
```

**Comment by jennybc** [comment]
BTW thanks for providing the workbook. That made this an easy "investigate over coffee" situation vs. languishing for months.

**Comment by rwbaer** [comment]
> BTW thanks for providing the workbook. That made this an easy "investigate over coffee" situation vs. languishing for months.

Well that's why repex! Thanks for the quick response.  So, I'm pretty sure the commas were there because the file is written by instrumentation.  Thanks for pointing out it is destroyed by the time it hits the XML file.  Now I have to figure out if it easier to get Biotek to change how it writes data for these cells (probably) or get Microsoft to get Excel to stop helping (unlikely).

Anyway, thanks.  Maybe I'll just code around it in R 👍
