### ISSUE TITLE
excel_sheets with foreign letters in file name

### ISSUE THREAD

**Issue by bjorn81** [tidyverse/readxl#639]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

The excel_sheets function is not working for me when there are Swedish letters "ÅÄÖ" in the file names. However, the read_excel function does work

```r
fname <- "borlänge.xlsx"

wb <- read_excel(fname, sheet = 1) # works
sheets <- excel_sheets(fname) # BorlÃ¤nge.xlsx' cannot be opened.
```

**Comment by jennybc** [comment]
I am not able to reproduce this on my Windows machine.

``` r
devtools::load_all()
#> i Loading readxl

#fs::file_copy(readxl_example("datasets.xlsx"), "investigations/iss639-borlänge.xlsx")

wb <- read_excel("investigations/iss639-borlänge.xlsx", sheet = 1)
sheets <- excel_sheets("investigations/iss639-borlänge.xlsx")
sheets
#> [1] "iris"     "mtcars"   "chickwts" "quakes"
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

At this point, I'm going to be optimistic and hope that some of the many internal changes since Feb 2021 have actually fixed this path problem.

If, after installing the dev version of readxl, or after the next release (coming soon!), you still see this problem, please open a new issue.
