### ISSUE TITLE
 decimal number is converted to scientific form

### ISSUE THREAD

**Issue by kfhk** [tidyverse/readxl#673]
I met a bug while reading the file attached:
[forestplot.xlsx](https://github.com/tidyverse/readxl/files/7774474/forestplot.xlsx)

> forestplot <- read_xlsx("forestplot.xlsx");forestplot$P1
 [1] NA                      NA                                        
 [3] "＜0.01"                NA                     
 [5] NA                      "＜0.01"               
 [7] NA                      NA                     
 [9] "7.4999999999999997E-2" NA                     
[11] NA                      "6.7000000000000004E-2"

"7.4999999999999997E-2" should be shown as '0.075'
"6.7000000000000004E-2" should be shown as '0.067'
_options()_ function doesn't work.

i

**Comment by jennybc** [comment]
No, this is not a bug in readxl.

The `P1` column (column C in the spreadsheet) imports as character data, due to the entries like `"＜0.01"` in C4.

``` r
library(readxl)

dat <- read_xlsx("investigations/iss673-floating-point.xlsx")
dat
#> # A tibble: 12 × 11
#>    Charateristics CI1       P1       OR1    LL1    UL1 CI2   P2       OR2    LL2
#>    <chr>          <chr>     <chr>  <dbl>  <dbl>  <dbl> <chr> <chr>  <dbl>  <dbl>
#>  1 SUVmax         <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#>  2 ≤7.2           <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#>  3 ＞7.2          9.121 (3… ＜0.…  9.12   3.80  21.9   8.36… ＜0.…  8.37   3.42 
#>  4 PV             <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#>  5 ≤30            <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#>  6 ＞30           0.288 (0… ＜0.…  0.288  0.135  0.613 0.33… ＜0.…  0.336  0.146
#>  7 Age            <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#>  8 ≤60            <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#>  9 ＞60           2.594 (0… 7.49…  2.59   0.909  7.40  0.33… <NA>  NA     NA    
#> 10 PSA            <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#> 11 ≤20            <NA>      <NA>  NA     NA     NA     <NA>  <NA>  NA     NA    
#> 12 ＞20           2.006 (0… 6.70…  2.01   0.953  4.22  0.33… <NA>  NA     NA    
#> # … with 1 more variable: UL2 <dbl>
dat$P1
#>  [1] NA                      NA                      "＜0.01"               
#>  [4] NA                      NA                      "＜0.01"               
#>  [7] NA                      NA                      "7.4999999999999997E-2"
#> [10] NA                      NA                      "6.7000000000000004E-2"
```

<sup>Created on 2022-03-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

This causes the numeric cells, like C10, to be read as or converted to character. Here is the information on disk for the cell C10. The decision to display this as 0.075 is being made by the Microsoft Excel application. readxl or any other 3rd party tool reading this file does not have direct access to this formatting decision (even though it is a good one!).

``` xml
<c r="C10" s="8">
<v>7.4999999999999997E-2</v>
</c>
```

readxl could convert the value (inside the `<v> ... </v>`) to a floating point number, then back again to a string, but you would just get scientific notation again, unless we implemented some sort of formatting rules, which is currently not an explicit goal.

This is an inherent awkwardness of reading columns that mix character and numeric data. The `"list"` column type allows you to bring each cell in as its "best" type and then post-process in R.

Here's a quick read on the difference between what Excel *stores* and what it *displays*:
https://excel.tips.net/T001982_Precision_and_Number_Display.html
